# Generated by Django 3.2.25 on 2026-03-26 15:46

from django.db import migrations, models


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('product', 'Category')
    initial_categories = [
        '衣物',
        '零食',
        '生活用品',
        '娱乐用品',
        '饲料',
        '数码产品',
        '学习用品',
        '其他',
    ]
    for name in initial_categories:
        Category.objects.get_or_create(name=name, parent=None)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='关键词'),
        ),
        migrations.RunPython(create_initial_categories, migrations.RunPython.noop),
    ]
