# Generated by Django 3.2.25 on 2026-03-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0004_seed_initial_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('active', '销售中'), ('inactive', '已下架'), ('violated', '违规下架')], db_index=True, default='active', help_text='active:销售中, inactive:商家下架, violated:管理员强制下架', max_length=20, verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='用于快速切换商品上下架状态', verbose_name='快速上下架'),
        ),
    ]
