# Generated by Django 3.2.25 on 2026-03-27 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_seed_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('view', '浏览'), ('cart', '加购'), ('order', '下单'), ('review', '评价')], max_length=20, verbose_name='行为类型')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='行为权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_06cf67_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['product', 'created_at'], name='recommendat_product_ae7367_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['behavior_type'], name='recommendat_behavio_71953f_idx'),
        ),
    ]
